travis:
  secure:
    BINSTAR_TOKEN: H0pfAbwOkZdcBn42yHsIXwDMc91RyGpURfdhPkpexBvNcG+Ywd6ZhU3n378qCmoQ07Ry7fS+iCSwZgkWfTcVHeM2m3aluLDIjCopmbiIg5PxGPzq2YAhtyjxoFlLus8to97IeWoeBBdpI/XASg0moWhmfusl7sKnFY5iLYAH+Sp0/cHjdOcFukgNP5DgZth1kdOX5EQ8E6DpPEQ4HN/xLA9Gs5e9Jkq5ajxcnJDqu8OChbL9wtqTMla99cRRnfRr+FMnGQDs0kn4CbUQFivb9iwsjPm5cHhFi/h38sCq251CKO1jA/H3wojwoiLHKhQrhzQwJdyIAi+K6V7NSlWHuPg8v4oVt3V5Wwx7wVw/JMlP16ZpYhHih1skqXeUFm+Rh8oF6seHov2T2PfpFjN3N34piXtKRy4mEk5JGzoa4Rv6HLWAM4D47H2lIQROKEMiLxPVnyK88TDRS7UsBNy3oN8mNPEtBrfEbDnz/ZjiyF9rABpB53ckoEis1reeXqFWucjSD8xZLPj8Af5vGFPcWH0X0n09T08UBtvKxpkcfd9sFNMXNn6sE7oLKfxL1eF8wEVYZ4HF4smYQhkU7xoqYfEKuJ4LDK1epHeJNVrMr/SRILTqcfzO1g7E6uDen1LKUetCl20YrhczqcU//uc+ZqqxBVsQe/q9h62aypLLv5g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
