travis:
  secure:
    BINSTAR_TOKEN: MNc/S5vgxE2nM7rrQqOA+jNsW/xqgfmgArrelhFxvTq7K+wCIEFwKHfoorQ2K/OU9HPutGcyFsE37YWTEQh5SlPvWo00yc+li3vv+ByRLmC5HT3W2OipUw8OfjB3pvZmhfuEesvGZ6VSFpl3c5ef0l3BrE6e9yNFJWN8i0u3bIMZOeCfWwTsObUXVKKt5onkHQCYmincpAl8amdsPRnh5i6GEAeMbe0nWd6DOn4F0sYrXb5i5965GIDDcIymQJ1WhWXIzOAjUz7yz+FjG+xi8hmvd2DOct4LX2QiU68ZsQC23+Ld50y1qH/cLpATrGxL9ASi/yB6i8U5dWC//wA744EoCieJknq1BA1sAhTdtHx+yFyRvOCsQ2NS/eMRJXf//h2a6GBZxqv5cka28eZv7Mmhe5R1lBWw5IhIyB8t+sQAYZKAICklB/ve4nqwoN92ZRKPHFKBw3F7JTjhP6BXLgLo6ZFEYStiBIq4rujpf4Cz0HdBDg4IU9OeiQd8AeBjfjBNrSfWtMjD7XOuFNxxIzsFgW/0Ygy0GioPUhAY6Rv5PPZLqDAWac3kxbfavZTM6pw/uqpQ2Owe6gq3Xw1bgy8SilUNYgQ86JPqqIeZ8Q9+yO0FVDpRmfA51eAHVBnoe0QJie2Si3qFsegcC7VDoW6cEobzVS0TSmSU5thhAYU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
